### ISSUE TITLE
Error pri databazovej migracii 

### ISSUE THREAD

**Issue by mirelon** [DreamTeam2/frisbee-turnaje#5]
$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/miso/.local/lib/python2.7/site-packages/django/core/management/**init**.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/miso/.local/lib/python2.7/site-packages/django/core/management/**init**.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/home/miso/.local/lib/python2.7/site-packages/django/conf/**init**.py", line 55, in **getattr**
    self._setup(name)
  File "/home/miso/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/miso/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in **init**
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/miso/workspace/frisbee-turnaje/Frisbee/Frisbee/settings.py", line 101, in <module>
    'django.core.context_processors.request',
TypeError: can only concatenate list (not "tuple") to list

**Comment by mirelon** [comment]
Problem je, ze TEMPLATE_CONTEXT_PROCESSORS = TCP + (
     'django.core.context_processors.request',
) nema byt s gulatymi zatvorkami, ale s hranatymi. Neviem, ako vam mohla vlastne zbehnut migracia, ved sa to takto nedalo spustit. Skuste, ci to po tejto oprave ide aj vam, lebo je mozne, ze je to sposobene nejakym rozdielom vo verzii niecoho.

**Comment by loveohno13** [comment]
Replace

`TEMPLATE_CONTEXT_PROCESSORS = TCP + (
'django.core.context_processors.request',
)`

to
`TEMPLATE_CONTEXT_PROCESSORS = TCP + [
'django.core.context_processors.request',
]`

It worked for me.

**Comment by mirelon** [comment]
Thanks, that solution is already done in 415ff01
