### ISSUE TITLE
Exception pri pridavani kategorii turnaja cez Kategorie turnajov -> Pridat

### ISSUE THREAD

**Issue by mirelon** [DreamTeam2/frisbee-turnaje#9]
Je to ValidationError:

ValidationError: [u'ManagementForm data is missing or has been tampered with']

Vyzera to na toto: http://stackoverflow.com/questions/25331500/managementform-data-is-missing-or-has-been-tampered-with

**Comment by mirelon** [comment]
Internal Server Error: /admin/kategoriaTurnaju/kategoriaturnaju/add/
Traceback (most recent call last):
  File "/home/miso/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miso/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/miso/.local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(_args, *_kwargs)
  File "/home/miso/.local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/home/miso/.local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, _args, *_kwargs)
  File "/home/miso/.local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, _args, *_kwargs)
  File "/home/miso/.local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1435, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/miso/.local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(_args, *_kwargs)
  File "/home/miso/.local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/home/miso/.local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(_args2, *_kwargs2)
  File "/home/miso/.local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(_args, *_kwargs)
  File "/home/miso/.local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1376, in changeform_view
    formsets, inline_instances = self._create_formsets(request, new_object, change=not add)
  File "/home/miso/.local/lib/python2.7/site-packages/super_inlines/admin.py", line 96, in _create_formsets
    if any(new_form.has_changed() for new_formset in new_formsets
  File "/home/miso/.local/lib/python2.7/site-packages/super_inlines/admin.py", line 97, in <genexpr>
    for new_form in new_formset):
  File "/home/miso/.local/lib/python2.7/site-packages/django/forms/formsets.py", line 74, in __iter__
    return iter(self.forms)
  File "/home/miso/.local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in **get**
    res = instance.**dict**[self.name] = self.func(instance)
  File "/home/miso/.local/lib/python2.7/site-packages/django/forms/formsets.py", line 144, in forms
    for i in range(self.total_form_count())]
  File "/home/miso/.local/lib/python2.7/site-packages/django/forms/formsets.py", line 116, in total_form_count
    return min(self.management_form.cleaned_data[TOTAL_FORM_COUNT], self.absolute_max)
  File "/home/miso/.local/lib/python2.7/site-packages/django/forms/formsets.py", line 98, in management_form
    code='missing_management_form',
ValidationError: [u'ManagementForm data is missing or has been tampered with']

**Comment by mirelon** [comment]
Asi sa to stalo pocas nejakej zlej manipulacie s formularmi. Ked to pridavam teraz, tak to ide. Navyse, tento usacase sa aj tak bude robit v detaile konkretneho turnaja, co je vedlajsia polozka v menu...
